export const CHANGE_QUESTION_LIST = 'CHANGE_QUEATION_LIST'
export const CHANGE_TOP_LIST = 'CHANGE_TOP_LIST'
export const CHANGE_PAGE_COUNT = 'CHANGE_PAGE_COUNT'

export const FETCH_QUESTION_LIST = 'FETCH_QUESTION_LIST'